# Generated by Django 6.1 on 2026-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_starred_by_alter_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
