# Generated by Django 6.1 on 2026-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='education/logos/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience/logos/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience/photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
